[workspace]
members = [
    "crates/anchor",
    "crates/http_api",
    "crates/world_state",
    "apps/app",
]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.14", default-features = false, features = [
    "bevy_winit",
    "multi-threaded",
    "bevy_render",
    "bevy_sprite",
    "bevy_core_pipeline"
] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
glam = "0.27"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
axum = "0.7"
