[package]
name = "app_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
anchor.workspace = true
serde.workspace = true
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
