[package]
name = "neural_renderer"
version = "0.1.0"
edition.workspace = true

[dependencies]
thiserror.workspace = true
world_state = { path = "../world_state" }
serde = { workspace = true, features = ["derive"] }
tracing.workspace = true

[dev-dependencies]
anyhow.workspace = true
