[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
tracing-subscriber.workspace = true
anchor.workspace = true
http_api.workspace = true
app_core.workspace = true
clap = { version = "4", features = ["derive"] }
